-- -----------------------------------------------------------------------------------
-- File Name    : https://oracle-base.com/dba/script_creation/role_ddl.sql
-- Author       : Tim Hall
-- Description  : Displays the DDL for a specific role.
-- Call Syntax  : @ddl_role (role)
-- Last Modified: 28/01/2006
--              : 26/03/2022 - Diogo Nomura - Edited to get all application roles
--                                          - Added spooling
-- -----------------------------------------------------------------------------------

set long 20000 longchunksize 20000 pagesize 0 linesize 1000 feedback off verify off trimspool on
column ddl format a1000

Var var1 varchar2(1000)

begin
select 'backup_roles'||'_'||a.host_name||'_'||a.instance_name||'_'||to_char(sysdate,'YYYY_MM_DD_HH24_MI_SS')||'.sql' into :var1
from v$instance a,
dual b;
end;
/

COLUMN spoolcol NEW_VALUE spoolname
SELECT :var1 AS spoolcol FROM DUAL;

spool &spoolname
spool

begin
   dbms_metadata.set_transform_param (dbms_metadata.session_transform, 'SQLTERMINATOR', true);
   dbms_metadata.set_transform_param (dbms_metadata.session_transform, 'PRETTY', true);
end;
/
 
-- variable v_role VARCHAR2(30);

-- exec :v_role := upper('&1');

select dbms_metadata.get_ddl('ROLE', r.role) AS ddl
from   dba_roles r
where  r.role not in (
'CONNECT','RESOURCE','DBA','PDB_DBA','AUDIT_ADMIN'
,'AUDIT_VIEWER','SELECT_CATALOG_ROLE','EXECUTE_CATALOG_ROLE','CAPTURE_ADMIN'
,'EXP_FULL_DATABASE','IMP_FULL_DATABASE','CDB_DBA','APPLICATION_TRACE_VIEWER'
,'LOGSTDBY_ADMINISTRATOR','DBFS_ROLE','GSMUSER_ROLE','GSMROOTUSER_ROLE'
,'AQ_ADMINISTRATOR_ROLE','AQ_USER_ROLE','DATAPUMP_EXP_FULL_DATABASE','DATAPUMP_IMP_FULL_DATABASE'
,'ADM_PARALLEL_EXECUTE_TASK','PROVISIONER','XS_SESSION_ADMIN','XS_NAMESPACE_ADMIN'
,'XS_CACHE_ADMIN','XS_CONNECT','GATHER_SYSTEM_STATISTICS','OPTIMIZER_PROCESSING_RATE'
,'DBMS_MDX_INTERNAL','BDSQL_ADMIN','BDSQL_USER','RECOVERY_CATALOG_OWNER'
,'RECOVERY_CATALOG_OWNER_VPD','RECOVERY_CATALOG_USER','EM_EXPRESS_BASIC','EM_EXPRESS_ALL'
,'SYSUMF_ROLE','SCHEDULER_ADMIN','HS_ADMIN_SELECT_ROLE','HS_ADMIN_EXECUTE_ROLE'
,'HS_ADMIN_ROLE','GLOBAL_AQ_USER_ROLE','OEM_ADVISOR','OEM_MONITOR'
,'JAVAIDPRIV','GSMADMIN_ROLE','GSM_POOLADMIN_ROLE','GDS_CATALOG_SELECT'
,'GGSYS_ROLE','XDBADMIN','XDB_SET_INVOKER','AUTHENTICATEDUSER'
,'XDB_WEBSERVICES','XDB_WEBSERVICES_WITH_PUBLIC','XDB_WEBSERVICES_OVER_HTTP','SODA_APP'
,'DATAPATCH_ROLE','WM_ADMIN_ROLE','JAVAUSERPRIV','RDFCTX_ADMIN'
,'JAVASYSPRIV','AVADEBUGPRIV','JAVADEBUGPRIV','EJBCLIENT'
,'JMXSERVER','DBJAVASCRIPT','JAVA_ADMIN','CTXAPP'
,'ORDADMIN','OLAP_XS_ADMIN','OLAP_DBA','OLAP_USER','GGS_GGSUSER_ROLE'
)
union all
select dbms_metadata.get_granted_ddl('ROLE_GRANT', rp.grantee) AS ddl
from   dba_role_privs rp
where  rp.grantee in (
    select r.role
    from   dba_roles r
    where  r.role not in (
        'CONNECT','RESOURCE','DBA','PDB_DBA','AUDIT_ADMIN'
        ,'AUDIT_VIEWER','SELECT_CATALOG_ROLE','EXECUTE_CATALOG_ROLE','CAPTURE_ADMIN'
        ,'EXP_FULL_DATABASE','IMP_FULL_DATABASE','CDB_DBA','APPLICATION_TRACE_VIEWER'
        ,'LOGSTDBY_ADMINISTRATOR','DBFS_ROLE','GSMUSER_ROLE','GSMROOTUSER_ROLE'
        ,'AQ_ADMINISTRATOR_ROLE','AQ_USER_ROLE','DATAPUMP_EXP_FULL_DATABASE','DATAPUMP_IMP_FULL_DATABASE'
        ,'ADM_PARALLEL_EXECUTE_TASK','PROVISIONER','XS_SESSION_ADMIN','XS_NAMESPACE_ADMIN'
        ,'XS_CACHE_ADMIN','XS_CONNECT','GATHER_SYSTEM_STATISTICS','OPTIMIZER_PROCESSING_RATE'
        ,'DBMS_MDX_INTERNAL','BDSQL_ADMIN','BDSQL_USER','RECOVERY_CATALOG_OWNER'
        ,'RECOVERY_CATALOG_OWNER_VPD','RECOVERY_CATALOG_USER','EM_EXPRESS_BASIC','EM_EXPRESS_ALL'
        ,'SYSUMF_ROLE','SCHEDULER_ADMIN','HS_ADMIN_SELECT_ROLE','HS_ADMIN_EXECUTE_ROLE'
        ,'HS_ADMIN_ROLE','GLOBAL_AQ_USER_ROLE','OEM_ADVISOR','OEM_MONITOR'
        ,'JAVAIDPRIV','GSMADMIN_ROLE','GSM_POOLADMIN_ROLE','GDS_CATALOG_SELECT'
        ,'GGSYS_ROLE','XDBADMIN','XDB_SET_INVOKER','AUTHENTICATEDUSER'
        ,'XDB_WEBSERVICES','XDB_WEBSERVICES_WITH_PUBLIC','XDB_WEBSERVICES_OVER_HTTP','SODA_APP'
        ,'DATAPATCH_ROLE','WM_ADMIN_ROLE','JAVAUSERPRIV','RDFCTX_ADMIN'
        ,'JAVASYSPRIV','AVADEBUGPRIV','JAVADEBUGPRIV','EJBCLIENT'
        ,'JMXSERVER','DBJAVASCRIPT','JAVA_ADMIN','CTXAPP'
        ,'ORDADMIN','OLAP_XS_ADMIN','OLAP_DBA','OLAP_USER','GGS_GGSUSER_ROLE'
    )
)
and    rownum = 1
union all
select dbms_metadata.get_granted_ddl('SYSTEM_GRANT', sp.grantee) AS ddl
from   dba_sys_privs sp
where  sp.grantee in (
    select r.role
    from   dba_roles r
    where  r.role not in (
        'CONNECT','RESOURCE','DBA','PDB_DBA','AUDIT_ADMIN'
        ,'AUDIT_VIEWER','SELECT_CATALOG_ROLE','EXECUTE_CATALOG_ROLE','CAPTURE_ADMIN'
        ,'EXP_FULL_DATABASE','IMP_FULL_DATABASE','CDB_DBA','APPLICATION_TRACE_VIEWER'
        ,'LOGSTDBY_ADMINISTRATOR','DBFS_ROLE','GSMUSER_ROLE','GSMROOTUSER_ROLE'
        ,'AQ_ADMINISTRATOR_ROLE','AQ_USER_ROLE','DATAPUMP_EXP_FULL_DATABASE','DATAPUMP_IMP_FULL_DATABASE'
        ,'ADM_PARALLEL_EXECUTE_TASK','PROVISIONER','XS_SESSION_ADMIN','XS_NAMESPACE_ADMIN'
        ,'XS_CACHE_ADMIN','XS_CONNECT','GATHER_SYSTEM_STATISTICS','OPTIMIZER_PROCESSING_RATE'
        ,'DBMS_MDX_INTERNAL','BDSQL_ADMIN','BDSQL_USER','RECOVERY_CATALOG_OWNER'
        ,'RECOVERY_CATALOG_OWNER_VPD','RECOVERY_CATALOG_USER','EM_EXPRESS_BASIC','EM_EXPRESS_ALL'
        ,'SYSUMF_ROLE','SCHEDULER_ADMIN','HS_ADMIN_SELECT_ROLE','HS_ADMIN_EXECUTE_ROLE'
        ,'HS_ADMIN_ROLE','GLOBAL_AQ_USER_ROLE','OEM_ADVISOR','OEM_MONITOR'
        ,'JAVAIDPRIV','GSMADMIN_ROLE','GSM_POOLADMIN_ROLE','GDS_CATALOG_SELECT'
        ,'GGSYS_ROLE','XDBADMIN','XDB_SET_INVOKER','AUTHENTICATEDUSER'
        ,'XDB_WEBSERVICES','XDB_WEBSERVICES_WITH_PUBLIC','XDB_WEBSERVICES_OVER_HTTP','SODA_APP'
        ,'DATAPATCH_ROLE','WM_ADMIN_ROLE','JAVAUSERPRIV','RDFCTX_ADMIN'
        ,'JAVASYSPRIV','AVADEBUGPRIV','JAVADEBUGPRIV','EJBCLIENT'
        ,'JMXSERVER','DBJAVASCRIPT','JAVA_ADMIN','CTXAPP'
        ,'ORDADMIN','OLAP_XS_ADMIN','OLAP_DBA','OLAP_USER','GGS_GGSUSER_ROLE'
        )
    )
and    rownum = 1
union all
select dbms_metadata.get_granted_ddl('OBJECT_GRANT', tp.grantee) AS ddl
from   dba_tab_privs tp
where  tp.grantee in (
    select r.role
    from   dba_roles r
    where  r.role not in (
        'CONNECT','RESOURCE','DBA','PDB_DBA','AUDIT_ADMIN'
        ,'AUDIT_VIEWER','SELECT_CATALOG_ROLE','EXECUTE_CATALOG_ROLE','CAPTURE_ADMIN'
        ,'EXP_FULL_DATABASE','IMP_FULL_DATABASE','CDB_DBA','APPLICATION_TRACE_VIEWER'
        ,'LOGSTDBY_ADMINISTRATOR','DBFS_ROLE','GSMUSER_ROLE','GSMROOTUSER_ROLE'
        ,'AQ_ADMINISTRATOR_ROLE','AQ_USER_ROLE','DATAPUMP_EXP_FULL_DATABASE','DATAPUMP_IMP_FULL_DATABASE'
        ,'ADM_PARALLEL_EXECUTE_TASK','PROVISIONER','XS_SESSION_ADMIN','XS_NAMESPACE_ADMIN'
        ,'XS_CACHE_ADMIN','XS_CONNECT','GATHER_SYSTEM_STATISTICS','OPTIMIZER_PROCESSING_RATE'
        ,'DBMS_MDX_INTERNAL','BDSQL_ADMIN','BDSQL_USER','RECOVERY_CATALOG_OWNER'
        ,'RECOVERY_CATALOG_OWNER_VPD','RECOVERY_CATALOG_USER','EM_EXPRESS_BASIC','EM_EXPRESS_ALL'
        ,'SYSUMF_ROLE','SCHEDULER_ADMIN','HS_ADMIN_SELECT_ROLE','HS_ADMIN_EXECUTE_ROLE'
        ,'HS_ADMIN_ROLE','GLOBAL_AQ_USER_ROLE','OEM_ADVISOR','OEM_MONITOR'
        ,'JAVAIDPRIV','GSMADMIN_ROLE','GSM_POOLADMIN_ROLE','GDS_CATALOG_SELECT'
        ,'GGSYS_ROLE','XDBADMIN','XDB_SET_INVOKER','AUTHENTICATEDUSER'
        ,'XDB_WEBSERVICES','XDB_WEBSERVICES_WITH_PUBLIC','XDB_WEBSERVICES_OVER_HTTP','SODA_APP'
        ,'DATAPATCH_ROLE','WM_ADMIN_ROLE','JAVAUSERPRIV','RDFCTX_ADMIN'
        ,'JAVASYSPRIV','AVADEBUGPRIV','JAVADEBUGPRIV','EJBCLIENT'
        ,'JMXSERVER','DBJAVASCRIPT','JAVA_ADMIN','CTXAPP'
        ,'ORDADMIN','OLAP_XS_ADMIN','OLAP_DBA','OLAP_USER','GGS_GGSUSER_ROLE'
        )
    )
and    rownum = 1
/

set linesize 80 pagesize 14 feedback on verify on

spool off